### ISSUE TITLE
HacGUI crash fix

### ISSUE THREAD

**Issue by GhandiJunior** [shadowninja108/HACGUI#8]
Hi 
I tried using HACGUI but i made a stupid mistake with locating some of the files.
now when i try to start up to try again the program keeps giving me öops something went wrong. what do i need to do to start up the program again?

Thanks

**Comment by shadowninja108** [comment]
You can go to %userprofile%/.switch and delete a file there to restart the process. So that I can fix the bug, what did you do to get that crash to occur, and what does the window say? (Copy the entire text if possible)

**Comment by DanielC7205** [comment]
Uhh shouldn't this be closed? @GhandiJunior @shadowninja108

**Comment by edgar1016** [comment]
Mine also crashes whenever trying to get keys I get the following error
`System.AggregateException: One or more errors occurred. ---> System.IO.InvalidDataException: Failed to decrypt package2! Is the correct key present?
   at LibHac.Package2.FindKeyGeneration(Keyset keyset, IStorage storage)
   at LibHac.Package2..ctor(Keyset keyset, IStorage storage)
   at HACGUI.FirstStart.PickNANDPage.OnNandFound() in B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\PickNANDPage.xaml.cs:line 119
   at HACGUI.FirstStart.PickNANDPage.<StartDeriving>b__2_1(DerivingPage page) in B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\PickNANDPage.xaml.cs:line 91
   at HACGUI.FirstStart.DerivingPage.<>c__DisplayClass0_0.<.ctor>b__1() in B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\DerivingPage.xaml.cs:line 24
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.InvalidDataException: Failed to decrypt package2! Is the correct key present?
   at LibHac.Package2.FindKeyGeneration(Keyset keyset, IStorage storage)
   at LibHac.Package2..ctor(Keyset keyset, IStorage storage)
   at HACGUI.FirstStart.PickNANDPage.OnNandFound() in B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\PickNANDPage.xaml.cs:line 119
   at HACGUI.FirstStart.PickNANDPage.<StartDeriving>b__2_1(DerivingPage page) in B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\PickNANDPage.xaml.cs:line 91
   at HACGUI.FirstStart.DerivingPage.<>c__DisplayClass0_0.<.ctor>b__1() in B:\Documents\Switch_Projects\hactoolgui\hactoolgui\FirstStart\DerivingPage.xaml.cs:line 24
   at System.Threading.Tasks.Task.Execute()<---`

I noticed if I delete all the files and start again it keeps remembering my console name and backup folder, sd inserted, and fuse dumps is always green I deleted the .switch folder as well same result.

After trying a second time it crashes again this time with time with the error saying sdservicestop it crashes and won't let me copy the report.
